apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-helm-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: redis
    targetRevision: 17.11.3  # Use the desired version of the chart
    helm:
      releaseName: redis
      parameters:
        - name: password
          value: "your-redis-password"  # Set your Redis password here
        - name: replication.enabled
          value: "true"
        - name: replication.slaveCount
          value: "2"  # Number of replicas you want to create
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true