apiVersion: v1
kind: Service
metadata:
  name: products
  labels:
    app: products
    service: products
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: products
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-products
  labels:
    account: products
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-v1
  labels:
    app: products
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
      version: v1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9080"
        prometheus.io/path: "/metrics"
      labels:
        app: products
        version: v1
    spec:
      serviceAccountName: bookinfo-products
      containers:
      - name: products
        image: docker.io/istio/examples-bookinfo-productpage-v1:1.20.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
